spring.application.name=BackenExT

spring.datasource.url=jdbc:mysql://localhost:3306/react
spring.datasource.username=root
spring.datasource.password=Sush@7517

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=youadhfajdhfuajhdajjvavjaivjadsnijvhadsjajfasdnfjads
